[technote]
id = "RTN-071"
series_id = "RTN"
canonical_url = "https://rtn-071.lsst.io"
github_url = "https://github.com/lsst/rtn-071"
github_default_branch = "main"
date_created = 2024-01-17T22:45:12Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Leanne P."
name.family = "Guy"
orcid = "https://orcid.org/0000-0003-0800-8755"
internal_id = "guylp"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson AZ, 85719, USA"
